name: isort Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source repository
        uses: actions/checkout@v3
      - name: Run isort
        uses: isort/isort-action@v1